default_model_filename: "irra_rstp_text_encoder.plan"
name: "irra_rstp_text_encoder"
platform: "tensorrt_plan"
max_batch_size: 32
input [
  {
    name: "text"
    data_type: TYPE_INT32
    dims: [ 77 ]
  }
]
output [
  {
    name: "text_features"
    data_type: TYPE_FP32
    dims: [ 512 ]
  }
]
